# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  utility_config = release
  baremetal_config = release
  test_config = release
endif
ifeq ($(config),debug)
  utility_config = debug
  baremetal_config = debug
  test_config = debug
endif

PROJECTS := utility baremetal test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

utility:
ifneq (,$(utility_config))
	@echo "==== Building utility ($(utility_config)) ===="
	@${MAKE} --no-print-directory -C source/utility -f Makefile config=$(utility_config)
endif

baremetal: utility
ifneq (,$(baremetal_config))
	@echo "==== Building baremetal ($(baremetal_config)) ===="
	@${MAKE} --no-print-directory -C source/baremetal -f Makefile config=$(baremetal_config)
endif

test: baremetal utility
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C test -f Makefile config=$(test_config)
endif

clean:
	@${MAKE} --no-print-directory -C source/utility -f Makefile clean
	@${MAKE} --no-print-directory -C source/baremetal -f Makefile clean
	@${MAKE} --no-print-directory -C test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   utility"
	@echo "   baremetal"
	@echo "   test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"